apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogapp
      version: blue
  template:
    metadata:
      labels:
        app: blogapp
        version: blue
    spec:
      containers:
      - name: blogapp
        image: awsd43/blogapp:blue # Adjust the image tag for the blue version
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
