apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldencatbankapp
spec:
  destination:
    name: ''
    namespace: webapps
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/devopsenggr/GoldenCat-BankApp.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
